name: Business Office Asia
favicon: null
layout_spectrum: 0.27856161585077643
typography_spectrum: 0.49168
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7b7b7b'
    - '#010103'
    - '#444444'
    - '#ffffff'
    - '#95e7eb'
  brandStrength: 0.5
  lightness: 0.9555361655075103
  saturation: 0.5909309226553887
  rhythmicContrast: 0.27776088239625096
purpose: []
