name: Business Office Asia
favicon: null
layout_spectrum: 0.27856161585077643
typography_spectrum: 0.999193815747276
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.30000216886401176
  lightness: 0.9555361655075103
  saturation: 0.5909309226553887
  rhythmicContrast: 0.27776088239625096
purpose: []
